version: "3.1"
services:
  web:
    image: odoo:14.0-test
    build:
      context: .
      args:
        ODOO_ENV: "dev"
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./web_healthcheck:/usr/local/lib/python3.7/dist-packages/odoo/addons/web_healthcheck/
    environment:
      - DB_PASSWORD=odoo
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
